# Generated by Django 4.1 on 2022-12-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='file',
            field=models.FileField(max_length=200, null=True, upload_to=''),
        ),
    ]
