# Generated by Django 4.1 on 2022-12-10 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyManagementApp', '0002_research_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='file',
            field=models.FileField(max_length=200, null=True, upload_to='researches', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
